apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-secrets
type: Opaque
data:
  JWT_SECRET: PVd2M29QOG05UXpYUkxwNUE2Uzd1TjJ5QjR2RTFnSzhqRjBoTTNkSTZvQTg9
  SMTP_USER: OTg0MDI2OGM0NGYwOGE=
  SMTP_PASS: ZmM2YjI4NjRjNGZhZTI=
  DB_PASSWORD: cGFzcw==