apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-service
spec:
  selector:
    app: gatekeeper
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP          
